### PR TITLE
BiomedNMR changes

### PR DESCRIPTION
**Pull request by hcmh**
Hi Sebastian,

we are finally at the stage where we can begin to think about making our aura into a submodule. That also means that we finally have merged our changes with your git.

It really is a ton of code, and not all changes are simply additional files: Some also change aura functionality (I thinking about device_malloc_dependent and the device_range type 

One thing that is still missing from this pull request is adapting aura to the memory function changes. But I wanted to open this pull request already so that we can start discussing how to proceed.

Best wishes!

### CODE REVIEW

**Comment by sschaetz** [comment]
Hi Christian,

thanks for this - it is really awesome to see all this work come back to Aura. 

Proposal for how to proceed: I'll merge locally, make changes where I think they should be made or must be made, test and then.. I'm not sure acutally what then. 

I guess I can merge then. Or I can put up another branch that you can pull, integrate and test in BiomedNMR as well, update this pull request and then I'll merge.

Ideas?

Sebastian

**Comment by hcmh** [comment]
Not sure which way is easier. Maybe if you find changes, you can see whether it's easier to integrate them into this pull request or just merge them afterwards? 

Adding them to the pull request is probably a bit cleaner, I think, since then the repository is functional after committing it. But just committing the changes yourself afterwards might be more convenient. 
I don't know, really.
I think I'd prefer the updated pull request, but it really does not matter that much.

**Comment by sschaetz** [comment]
Yea, let's do it in a clean way.

**Comment by sschaetz** [comment]
Questions:

/home/sschaet/aura/include/boost/aura/device_range.hpp
The constructor from a const device_array has a FIXME - I don't understand it.

split_interleaved.hpp includes
#include "split_interleaved_s2i_kernels.hpp"
#include "split_interleaved_i2s_kernels.hpp"

Are these generated?

Do all unit tests pass (in OpenCL) in your branch? Run 
make all && ctest 
to verify.

**Comment by hcmh** [comment]
Partial answers ( :smile: ) :

This split_interleaved_*_kernels.hpp are supposed to be autogenerated (although probably only one of them. No need to have two, I think. I think. however, that the current generate_kernels.py does not autogenerate them.

The unit tests do not pass, they can't because I haven't changed our kernel invocations to use the new memory functions. That's one thing I'll need to change before merging.

And the device_range constructor: I actually missed that when integrating the changes. That's one of Til's changes, so I am not 100% sure. But here is what I think the problem was:
When creating a device_range from a const device_array, we would like to get back a const device_range. Otherwise, two things happen:
1) We implicitly and silently remove the const (or render it ineffectual). Even though we had a const device_array, we suddenly can modify its contents by using the device_range.
2) We have to remember to always use somthing like const auto drange = device_range(cdarray) for const device_array cdarray. So we need to explicilty mark it const, and we need to remember that cdarray was const to begin with.

What we really want is a constructor that returns a const device_range. Unfortunately in C++, return type specifications are not allowed for constructors. So we don't know how to work around that problem, since both ways of using it seem counter-intuitive. Do you have a better idea on how to achieve that? Maybe a conversion operator instead of constructor might work? But I think we tried that and that also somehow lost the const when assigning to an auto variable. Might be wrong about this, though.

Anyway, I'll change the kernel invocations now so that the unit tests start passing. Getting all of them to pass will be a bit more work though, since some of them really _should_ pass but don't (norm2 is an offender here, for example: The function does the right thing, but for large arrays the floating point values of CPU and  GPU calculation differ, so it fails. Even thought the values are of so close... meh). And there as some more of that, so it'll be a while before this is really finished enough to be merged.

**Comment by hcmh** [comment]
Ok, so now most unit tests pass. Full "transcript" is [here.](https://gist.github.com/hcmh/ff394a8d390867f0bd6b)
So all the math tests pass, the only failures are device_lock (an expected failure if I understand it correctly) and device_range.

So device_range first: It fails in line 22 `BOOST_CHECK(range1.begin() == range2.begin());`
So the device_ptr's are not equal. I checked more closely, and the `memory` is the member that is different. But I really don't know why. Could you take a look, maybe you can see why?

And then device_lock: First, I really don't get the test. Both `fork`ed processes create 2 exclusive devices. On a machine with 8 devices that should work fine, I think. But it does fail.
It runs the following code:

``` C++

inline device create_device_exclusive()
{
    int num = device_get_count();
    for (std::size_t n=0; n<device_get_count(); n++) {
        auto dl = create_device_lock(num);
        if (dl) {
            return device(n, dl);
        }
    }
    throw "no device available!";
}
```

which tries `num` times to create a lock for device `num`. Not for device `n`. Is that intentional? 

Greetings,
Christian

edit: By the way, I'll be gone from Sunday to Thursday, so it might be a while before I answer.

**Comment by sschaetz** [comment]
Thanks for your awesome work guys.

**Pull request merged**
